export const enums = {
  POLICY_NUMBER: "policyNumber",
  FIRST_NAME: "firstName",
  LAST_NAME: "lastName",
  PHONE_TYPE: "phoneType",
  PHONE_NUMBER: "phoneNumber",
  EMAIL: "email",
  ADDRESS_LINE_1: "addressLine1",
  ADDRESS_LINE_2: "addressLine2",
  CITY: "city",
  STATE: "state",
  ZIP: "zip",
  DATE_OF_LOSS: "dateOfLoss",
  TIME_OF_LOSS: "timeOfLoss",
  LOSS_REPORTER: "lossReporter",
  LOSS_LOCATION_1: "lossLocation1",
  LOSS_LOCATION_2: "lossLocation2",
  LOSS_CITY: "lossCity",
  LOSS_STATE: "lossState",
  LOSS_ZIP: "lossZip",
  LOSS_DESCRIPTION: "lossDescription",
};
